# Change these first
owner: settlin # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Settlin Webapp
    url: https://settlin.in
  - name: Settlin CRM
    url: $SETTLIN_PORTAL
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: webapp.status.settlin.in
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Settlin Webapp
  introTitle: "**Settlin** is the best way to buy or sell your property in Bangalore"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/settlin/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
